<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <PackageReference Include="System.Management" Version="7.0.2" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBox.Database.Tenant\IBox.Database.Tenant.csproj" />
    <ProjectReference Include="..\IBox.PageBuilder\IBox.PageBuilder.csproj" />
    <ProjectReference Include="..\IBox.Workflow\IBox.Workflow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Web.Administration">
      <HintPath>C:\Windows\System32\inetsrv\Microsoft.Web.Administration.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
